### ISSUE TITLE
Q: How to bundle this example into one .exe file ?

### ISSUE THREAD

**Issue by tjyang** [security-union/yew-weather#3]
I looked up [trunk commands](https://trunkrs.dev/commands/). It only has  trunk build/serve function.
Is there is a way to build all the assets into one binary file ?

**Comment by darioalessandro** [comment]
Trunk build does create a static folder with all the assets, I forgot how’s it called, either build or dist

**Comment by darioalessandro** [comment]
Yo I’ll need to create a zip with all those assets

**Comment by darioalessandro** [comment]
I just confirmed, the folder is called dist and it contains the static website ready to be served using any web server

<img width="697" alt="Schermata 2022-08-06 alle 9 19 27 PM" src="https://user-images.githubusercontent.com/1176339/183271056-f61c215e-4bc3-40d0-b566-4007fa39d3da.png">
.

**Comment by tjyang** [comment]
I have a small rest client in python that answer query via cmd line arguments  or  web GUI under web server hosting. 
I am thinking of porting it over to Rust to lean more about Rust programming. Thanks the pointer to electron/Tauri. I will check them out.
