### ISSUE TITLE
Facing issue with Api call

### ISSUE THREAD

**Issue by Jyo561Python** [security-union/yew-weather#4]
The Api Call works with the api link of the code but when i tried it with OpenWeather Api it didnt why so?

**Comment by darioalessandro** [comment]
Hello @Jyo561Python !! 

By openweather api do you mean https://openweathermap.org/ ??

Are openweather apis interoperable with the USA Weather service API (api.weather.gov)?

Did you see any difference on the openweather responses?

**Comment by darioalessandro** [comment]
OP failed to reply?
